# docker build -t wfpb:glycosight-interface-base -f dockerfile.base .
FROM python:3.10-slim-buster

COPY ./requirements.txt /

RUN pip3 install -r requirements.txt && \
    mkdir -p /var/log/gunicorn

