# docker build -t wfpb-glycosight-interface-base -f dockerfile.interface.base .
FROM python:3.10-slim-buster

COPY requirements.txt glycosight_interface.py wsgi.py app.config /flask/

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    pip install -r /flask/requirements.txt && \
    mkdir -p /var/log/gunicorn

WORKDIR /flask
