# docker build -t glycosight-backend-base -f dockerfile.backend.base .
FROM glyomics/glycosight:1.1.0

USER root
COPY requirements.txt wsgi.py /flask/

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    rm -rf /data/config/ && \
    apt-get install -y python3-pip vim && \
    pip3 install --upgrade pip && \
    pip3 install -r /flask/requirements.txt && \
    mkdir -p /var/log/gunicorn

WORKDIR /flask
