# build with docker build -t wfpb-ui-initial dockerfile.ui.base .
FROM wfpb-ui-base:latest

COPY . /playbook
WORKDIR /playbook

RUN npm install && pip install --break-system-packages -r wfpb_requirements.txt

CMD ["npm", "run", "dev"]
