# build with docker build -t wfpb-ui-base -f dockerfile.wfpb.base .
FROM node:21.3.0

# Dependencies first!



RUN DEBIAN_FRONTEND=noninteractive apt update && \
    apt install -y python3-dev python3 python3-pip \
    vim curl && \
    mkdir /ufs && \
    cd /ufs && \
    git clone https://github.com/MaayanLab/ufs.git && \
    cd ufs && pip install --break-system-packages . && cd /


