# build with docker build -t wfpb-ui-base -f dockerfile.wfpb.base .
FROM node:21.3.0

# Dependencies first!

COPY ufs/ /ufs

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    apt install -y python3-dev python3 python3-pip \
    vim curl && \
    cd /ufs && \
    pip install --break-system-packages . && cd - /
